language: node_js
node_js:
  - 'node'
services:
  - docker
install:
  - npm install

script:
  - npm run build

after_success:
  - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
  - docker build -t abhidhamma91/disorder .
  - docker push abhidhamma91/disorder
