export default [
  { name: 'RED', color: '#F44336' },
  { name: 'PINK', color: '#E91E63' },
  { name: 'PURPLE', color: '#9C27B0' },
  { name: 'DEEPPURPLE', color: '#673AB7' },
  { name: 'WHALEBLUE', color: '#1A232C' },
  { name: 'INDEGO', color: '#3F51B5' },
  { name: 'FACEBLUE', color: '#3B5998' },
  { name: 'BLUE', color: '#2196F3' },
  { name: 'LIGHTBLUE', color: '#03A9F4' },
  { name: 'TEAL', color: '#009688' },
  { name: 'GREEN', color: '#4CAF50' },
  { name: 'LIGHTGREEN', color: '#8BC34A' },
  { name: 'LIME', color: '#CDDC39' },
  { name: 'YELLOW', color: '#FFEB3B' },
  { name: 'AMBER', color: '#FFC107' },
  { name: 'ORANGE', color: '#FF9800' },
  { name: 'DEEPORANGE', color: '#FF5722' },
  { name: 'BROWN', color: '#795548' },
  { name: 'GREY', color: '#9E9E9E' },
  { name: 'DEEPBLACK', color: '#1C1C1C' },
];
